// <auto-generated />
using BodyUpAPI.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BodyUpAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250930142803_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BodyUpAPI.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Udforsk vores udvalg af kosttilskud til styrke og muskelvækst",
                            Name = "Muskelopbygning",
                            Url = "/muskelopbygning"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Udforsk vores udvalg af sunde og lækre mad- og snackprodukter",
                            Name = "Mad & Snacks",
                            Url = "/mad-snacks"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Udforsk vores udvalg af energigivende kosttilskud",
                            Name = "Energi",
                            Url = "/muskelopbygning"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Udforsk vores udvalg af tilbehør",
                            Name = "Tilbehør",
                            Url = "/accessories"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Udforsk vores produkter som ikke er kategoriseret under de primære kategorier",
                            Name = "Andet",
                            Url = "/other"
                        });
                });

            modelBuilder.Entity("BodyUpAPI.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExternalProductId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Price")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Retailer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("BodyUpAPI.Models.ProductSubCategories", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("SubCategoryId")
                        .HasColumnType("int");

                    b.HasKey("ProductId", "SubCategoryId");

                    b.HasIndex("SubCategoryId");

                    b.ToTable("ProductSubCategories");
                });

            modelBuilder.Entity("BodyUpAPI.Models.SubCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Keywords")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SubCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Proteinpulver er et kosttilskud, der hjælper med muskelopbygning, restitution og at dække dit daglige proteinbehov. Perfekt til alle, der træner, vil optimere deres resultater eller har brug for ekstra protein i hverdagen.",
                            Keywords = "protein, whey, isolat, proteinpulver",
                            Name = "Proteinpulver",
                            Url = "/proteinpulver"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Kreatin er et populært kosttilskud blandt styrketrænere og atleter. Det hjælper med at øge styrke, eksplosivitet og muskelmasse ved at give musklerne mere energi under korte, intense træningspas. Kreatin findes naturligt i kød og fisk, men som pulver eller kapsler er det en praktisk måde at sikre optimal mængde på. Det er videnskabeligt dokumenteret, sikkert for de fleste voksne, og kan kombineres med proteinpulver for maksimal muskelvækst og restitution.",
                            Keywords = "kreatin, creatine, creapure",
                            Name = "Kreatin",
                            Url = "/kreatin"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Weight Gainer er et kosttilskud designet til at hjælpe med at tage på i vægt og opbygge muskelmasse. Det indeholder typisk en kombination af protein, kulhydrater og sunde fedtstoffer, som giver kroppen ekstra kalorier til at understøtte muskelvækst. Det er ideelt for personer, der har svært ved at spise nok gennem almindelig mad, f.eks. hurtigt stofskifte eller intensiv træning. Weight Gainer kan blandes i shakes, smoothies eller endda i madopskrifter, så det bliver nemt at få de nødvendige kalorier og proteiner.",
                            Keywords = "weight gainer, mass gainer, vægttilskud, gainer",
                            Name = "Weight gainer",
                            Url = "/weight-gainer"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Pre-Workout er et kosttilskud, der tages inden træning for at booste energi, fokus og udholdenhed. Det indeholder typisk koffein, aminosyrer og andre ingredienser, som hjælper dig med at yde dit bedste under intense træningspas. Pre-Workout er perfekt til dem, der vil have mere kraft, bedre koncentration og højere intensitet i deres træning. Det kan blandes med vand som en shake og tages ca. 20–30 minutter før træning.",
                            Keywords = "pre workout, preworkout",
                            Name = "Pre workout",
                            Url = "/pre-workout"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Proteinbarer er praktiske snacks, der hjælper dig med at få ekstra protein på farten. De er perfekte før eller efter træning, eller som et mellemmåltid, når du har brug for en hurtig energikilde. Proteinbarer indeholder typisk en blanding af protein, kulhydrater og lidt fedt, og findes i mange smagsvarianter, så det bliver både sundt og lækkert. De understøtter muskelopbygning, restitution og hjælper dig med at nå dit daglige proteinbehov.",
                            Keywords = "proteinbar, protein bar, barer, protein snack",
                            Name = "Proteinbarer",
                            Url = "/proteinbarer"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Elektrolytter er essentielle mineraler som natrium, kalium og magnesium, der hjælper kroppen med at opretholde væskebalance, nervefunktion og muskelsammentrækning. De er især vigtige under og efter træning, når du sveder og mister salte, og kan hjælpe med at forebygge kramper, træthed og dehydrering. Elektrolytter fås som pulver, tabletter eller drikke, og er en enkel måde at sikre optimal væskebalance på.",
                            Keywords = "elektrolyt, elektrolytter, electrolyte",
                            Name = "Elektrolytter",
                            Url = "/elektrolytter"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Energigel er et hurtigtoptageligt kosttilskud, der typisk anvendes under løb, cykling og andre udholdenhedssportsgrene. Gelen indeholder primært kulhydrater, som giver hurtig energi til musklerne og hjælper med at opretholde blodsukkeret under længerevarende træning eller konkurrence. Nogle gels indeholder også elektrolytter for at modvirke væsketab, eller koffein for at give ekstra fokus og energi.",
                            Keywords = "gel",
                            Name = "Gel",
                            Url = "/gel"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Shakers er uundværlige redskaber til at blande proteinpulver, kosttilskud og drikkevarer hurtigt og effektivt. De er designet med en tæt lukning og en indbygget si eller kugle, der hjælper med at nedbryde klumper og sikre en jævn konsistens. Shakers er ideelle til folk på farten, der ønsker en nem måde at forberede deres ernæringsdrikke på, hvad enten det er før eller efter træning. De fås i forskellige størrelser, materialer og designs, så du kan finde en, der passer til dine behov og stil.",
                            Keywords = "shaker, flaske, bottle, drikkedunk",
                            Name = "Shaker",
                            Url = "/shaker"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Udforsk vores produkter som ikke er kategoriseret under de primære kategorier",
                            Keywords = "",
                            Name = "Udenfor kategori",
                            Url = "/other"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Proteinbarer er praktiske snacks, der hjælper dig med at få ekstra protein på farten. De er perfekte før eller efter træning, eller som et mellemmåltid, når du har brug for en hurtig energikilde. Proteinbarer indeholder typisk en blanding af protein, kulhydrater og lidt fedt, og findes i mange smagsvarianter, så det bliver både sundt og lækkert. De understøtter muskelopbygning, restitution og hjælper dig med at nå dit daglige proteinbehov.",
                            Keywords = "snack, nødder, tørret frugt, bars, chips",
                            Name = "Snacks",
                            Url = "/snacks"
                        });
                });

            modelBuilder.Entity("BodyUpAPI.Models.SubCategoryCategories", b =>
                {
                    b.Property<int>("SubCategoryId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.HasKey("SubCategoryId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("SubCategoryCategories");

                    b.HasData(
                        new
                        {
                            SubCategoryId = 1,
                            CategoryId = 1
                        },
                        new
                        {
                            SubCategoryId = 2,
                            CategoryId = 1
                        },
                        new
                        {
                            SubCategoryId = 3,
                            CategoryId = 1
                        },
                        new
                        {
                            SubCategoryId = 4,
                            CategoryId = 1
                        },
                        new
                        {
                            SubCategoryId = 4,
                            CategoryId = 3
                        },
                        new
                        {
                            SubCategoryId = 5,
                            CategoryId = 1
                        },
                        new
                        {
                            SubCategoryId = 5,
                            CategoryId = 2
                        },
                        new
                        {
                            SubCategoryId = 6,
                            CategoryId = 3
                        },
                        new
                        {
                            SubCategoryId = 7,
                            CategoryId = 3
                        },
                        new
                        {
                            SubCategoryId = 8,
                            CategoryId = 4
                        },
                        new
                        {
                            SubCategoryId = 9,
                            CategoryId = 5
                        },
                        new
                        {
                            SubCategoryId = 10,
                            CategoryId = 2
                        });
                });

            modelBuilder.Entity("BodyUpAPI.Models.ProductSubCategories", b =>
                {
                    b.HasOne("BodyUpAPI.Models.Product", "Product")
                        .WithMany("ProductSubCategories")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BodyUpAPI.Models.SubCategory", "SubCategory")
                        .WithMany("ProductSubCategories")
                        .HasForeignKey("SubCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("SubCategory");
                });

            modelBuilder.Entity("BodyUpAPI.Models.SubCategoryCategories", b =>
                {
                    b.HasOne("BodyUpAPI.Models.Category", "Category")
                        .WithMany("SubCategoryCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BodyUpAPI.Models.SubCategory", "SubCategory")
                        .WithMany("SubCategoryCategories")
                        .HasForeignKey("SubCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("SubCategory");
                });

            modelBuilder.Entity("BodyUpAPI.Models.Category", b =>
                {
                    b.Navigation("SubCategoryCategories");
                });

            modelBuilder.Entity("BodyUpAPI.Models.Product", b =>
                {
                    b.Navigation("ProductSubCategories");
                });

            modelBuilder.Entity("BodyUpAPI.Models.SubCategory", b =>
                {
                    b.Navigation("ProductSubCategories");

                    b.Navigation("SubCategoryCategories");
                });
#pragma warning restore 612, 618
        }
    }
}
