// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProteinProAPI.Database;

#nullable disable

namespace ProteinProAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251020115742_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProteinProAPI.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Keywords")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Keywords = "protein, whey, isolat, proteinpulver",
                            Name = "Proteinpulver"
                        },
                        new
                        {
                            Id = 2,
                            Keywords = "kreatin, creatine, creapure",
                            Name = "Kreatin"
                        },
                        new
                        {
                            Id = 3,
                            Keywords = "weight gainer, mass gainer, vægttilskud, gainer",
                            Name = "Weight gainer"
                        },
                        new
                        {
                            Id = 4,
                            Keywords = "pre workout, preworkout",
                            Name = "Pre workout"
                        },
                        new
                        {
                            Id = 5,
                            Keywords = "proteinbar, protein bar, barer, protein snack",
                            Name = "Proteinbarer"
                        },
                        new
                        {
                            Id = 6,
                            Keywords = "elektrolyt, elektrolytter, electrolyte",
                            Name = "Elektrolytter"
                        },
                        new
                        {
                            Id = 7,
                            Keywords = "gel",
                            Name = "Gel"
                        },
                        new
                        {
                            Id = 8,
                            Keywords = "snack, nødder, tørret frugt, bars, chips",
                            Name = "Snacks"
                        },
                        new
                        {
                            Id = 9,
                            Keywords = "shaker, bottle",
                            Name = "Tilbehør"
                        },
                        new
                        {
                            Id = 10,
                            Keywords = "",
                            Name = "Andet"
                        });
                });

            modelBuilder.Entity("ProteinProAPI.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExternalProductId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Price")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Retailer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("ProteinProAPI.Models.Product", b =>
                {
                    b.HasOne("ProteinProAPI.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ProteinProAPI.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
